<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ $post->title }}</title>
</head>
<body>
    <h1>{{ $post->title }}</h1>
    <h4>In <em>{{ $post->category->name }}</em></h4>
    <p><strong>By </strong> {{ $post->user->first_name }} {{ $post->user->last_name }}</p>
    <p><strong>Posted on </strong> {{ $post->created_at->toDayDateTimeString() }}</p>
    <hr>

    <div>
        {{ $post->body }}
    </div>

    <hr>
    Generated by {{ config('app.name', 'CUEA411') }}
</body>
</html>